/**
 * 1.4.68: painterly 今日小事 illustrations — WebP assets under /vignette/{id}.webp
 * (soft light, dense foliage dabs; generated by scripts/gen-vignette-art.py).
 */
import { esc } from './util';

/** Daily-event ids that have a dedicated illustration. */
export const VIGNETTE_ART_IDS = [
  'mist',
  'compost',
  'birds',
  'drywind',
  'leaves',
  'drawing',
  'aphids',
  'sunbeam',
  'cat',
  'quiet',
] as const;

export type VignetteArtId = (typeof VIGNETTE_ART_IDS)[number];

const ART_SET = new Set<string>(VIGNETTE_ART_IDS);

/** Public URL for a vignette illustration (fallback: quiet). */
export function vignetteArtUrl(eventId: string): string {
  const id = ART_SET.has(eventId) ? eventId : 'quiet';
  return `/vignette/${id}.webp`;
}

/** Safe HTML fragment for the daily card modal. */
export function vignetteArtHtml(eventId: string): string {
  const id = ART_SET.has(eventId) ? eventId : 'quiet';
  return `<div class="vignette-art" data-vig="${esc(id)}"><img src="${esc(vignetteArtUrl(id))}" alt="" width="720" height="480" decoding="async" /></div>`;
}
